#!/bin/bash
clear
echo -e "\E[44;1;37m     INSTALANDO BOT SSH     \E[0m"
echo -e "\nINSTALANDO ESPERE...."
apt update -y > /dev/null 2>&1 && apt install unzip at jq curl -y > /dev/null 2>&1
mkdir $HOME/BOT
cd $HOME/BOT && wget https://www.dropbox.com/s/p0cxrt4x80ge6xj/curso%20bot.zip
unzip curso%20bot.zip > /dev/null 2>&1 && rm curso%20bot.zip > /dev/null 2>&1
chmod +x $(ls)
mv botteste /bin/botteste
clear && echo -e "INSTALADO CON EXITO !\nPARA ACTIVAR ESCRIBA ''botteste''
cd $HOME && rm inst-botteste > /dev/null 2>&1
